/**
 * SnfEnumUlkeler.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package org.datacontract.schemas._2004._07.KBS_Model;

public class SnfEnumUlkeler implements java.io.Serializable {
    private java.lang.String _value_;
    private static java.util.HashMap _table_ = new java.util.HashMap();

    // Constructor
    protected SnfEnumUlkeler(java.lang.String value) {
        _value_ = value;
        _table_.put(_value_,this);
    }

    public static final java.lang.String _TANIMSIZ = "TANIMSIZ";
    public static final java.lang.String _TURKIYE = "TURKIYE";
    public static final java.lang.String _AFGHANISTAN = "AFGHANISTAN";
    public static final java.lang.String _ALBANIA = "ALBANIA";
    public static final java.lang.String _ALGERIA = "ALGERIA";
    public static final java.lang.String _AMERICAN_SAMOA = "AMERICAN_SAMOA";
    public static final java.lang.String _ANDORRA = "ANDORRA";
    public static final java.lang.String _ANGOLA = "ANGOLA";
    public static final java.lang.String _ANGUILLA = "ANGUILLA";
    public static final java.lang.String _ANTARCTICA = "ANTARCTICA";
    public static final java.lang.String _ANTIGUA_AND_BARBUDA = "ANTIGUA_AND_BARBUDA";
    public static final java.lang.String _ARGENTINA = "ARGENTINA";
    public static final java.lang.String _ARMENIA = "ARMENIA";
    public static final java.lang.String _ARUBA = "ARUBA";
    public static final java.lang.String _AUSTRALIA = "AUSTRALIA";
    public static final java.lang.String _AUSTRIA = "AUSTRIA";
    public static final java.lang.String _AZERBAIJAN = "AZERBAIJAN";
    public static final java.lang.String _BAHAMAS = "BAHAMAS";
    public static final java.lang.String _BAHRAIN = "BAHRAIN";
    public static final java.lang.String _BANGLADESH = "BANGLADESH";
    public static final java.lang.String _BARBADOS = "BARBADOS";
    public static final java.lang.String _BELARUS = "BELARUS";
    public static final java.lang.String _BELGIUM = "BELGIUM";
    public static final java.lang.String _BELIZE = "BELIZE";
    public static final java.lang.String _BENIN = "BENIN";
    public static final java.lang.String _BERMUDA = "BERMUDA";
    public static final java.lang.String _BHUTAN = "BHUTAN";
    public static final java.lang.String _BOLIVIA = "BOLIVIA";
    public static final java.lang.String _BOSNIA_AND_HERZEGOVINA = "BOSNIA_AND_HERZEGOVINA";
    public static final java.lang.String _BOTSWANA = "BOTSWANA";
    public static final java.lang.String _BOUVET_ISLAND = "BOUVET_ISLAND";
    public static final java.lang.String _BRAZIL = "BRAZIL";
    public static final java.lang.String _BRITISH_INDIAN_OCEAN_TERRITORY = "BRITISH_INDIAN_OCEAN_TERRITORY";
    public static final java.lang.String _BRUNEI_DARUSSALAM = "BRUNEI_DARUSSALAM";
    public static final java.lang.String _BULGARIA = "BULGARIA";
    public static final java.lang.String _BURKINA_FASO = "BURKINA_FASO";
    public static final java.lang.String _BURUNDI = "BURUNDI";
    public static final java.lang.String _CAMBODIA = "CAMBODIA";
    public static final java.lang.String _CAMEROON = "CAMEROON";
    public static final java.lang.String _CANADA = "CANADA";
    public static final java.lang.String _CAPE_VERDE = "CAPE_VERDE";
    public static final java.lang.String _CAYMAN_ISLANDS = "CAYMAN_ISLANDS";
    public static final java.lang.String _CENTRAL_AFRICAN_REPUBLIC = "CENTRAL_AFRICAN_REPUBLIC";
    public static final java.lang.String _CHAD = "CHAD";
    public static final java.lang.String _CHILE = "CHILE";
    public static final java.lang.String _CHINA = "CHINA";
    public static final java.lang.String _CHRISTMAS_ISLAND = "CHRISTMAS_ISLAND";
    public static final java.lang.String _COCOS_KEELING_ISLANDS = "COCOS_KEELING_ISLANDS";
    public static final java.lang.String _COLOMBIA = "COLOMBIA";
    public static final java.lang.String _COMOROS = "COMOROS";
    public static final java.lang.String _CONGO_REPUBLIC_OF = "CONGO_REPUBLIC_OF";
    public static final java.lang.String _CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE_formerly_Zaire = "CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE_formerly_Zaire";
    public static final java.lang.String _COOK_ISLANDS = "COOK_ISLANDS";
    public static final java.lang.String _COSTA_RICA = "COSTA_RICA";
    public static final java.lang.String _CÔTE_DIVOIRE_Ivory_Coast = "CÔTE_DIVOIRE_Ivory_Coast";
    public static final java.lang.String _CROATIA_Hrvatska = "CROATIA_Hrvatska";
    public static final java.lang.String _CUBA = "CUBA";
    public static final java.lang.String _CYPRUS = "CYPRUS";
    public static final java.lang.String _CZECH_REPUBLIC = "CZECH_REPUBLIC";
    public static final java.lang.String _DENMARK = "DENMARK";
    public static final java.lang.String _DJIBOUTI = "DJIBOUTI";
    public static final java.lang.String _DOMINICA = "DOMINICA";
    public static final java.lang.String _DOMINICAN_REPUBLIC = "DOMINICAN_REPUBLIC";
    public static final java.lang.String _ECUADOR = "ECUADOR";
    public static final java.lang.String _EGYPT = "EGYPT";
    public static final java.lang.String _EL_SALVADOR = "EL_SALVADOR";
    public static final java.lang.String _EQUATORIAL_GUINEA = "EQUATORIAL_GUINEA";
    public static final java.lang.String _ERITREA = "ERITREA";
    public static final java.lang.String _ESTONIA = "ESTONIA";
    public static final java.lang.String _ETHIOPIA = "ETHIOPIA";
    public static final java.lang.String _FAEROE_ISLANDS = "FAEROE_ISLANDS";
    public static final java.lang.String _FALKLAND_ISLANDS_MALVINAS = "FALKLAND_ISLANDS_MALVINAS";
    public static final java.lang.String _FIJI = "FIJI";
    public static final java.lang.String _FINLAND = "FINLAND";
    public static final java.lang.String _FRANCE = "FRANCE";
    public static final java.lang.String _FRENCH_GUIANA = "FRENCH_GUIANA";
    public static final java.lang.String _FRENCH_POLYNESIA = "FRENCH_POLYNESIA";
    public static final java.lang.String _FRENCH_SOUTHERN_TERRITORIES = "FRENCH_SOUTHERN_TERRITORIES";
    public static final java.lang.String _GABON = "GABON";
    public static final java.lang.String _GAMBIA = "GAMBIA";
    public static final java.lang.String _GEORGIA = "GEORGIA";
    public static final java.lang.String _GERMANY = "GERMANY";
    public static final java.lang.String _GHANA = "GHANA";
    public static final java.lang.String _GIBRALTAR = "GIBRALTAR";
    public static final java.lang.String _GREECE = "GREECE";
    public static final java.lang.String _GREENLAND = "GREENLAND";
    public static final java.lang.String _GRENADA = "GRENADA";
    public static final java.lang.String _GUADELOUPE = "GUADELOUPE";
    public static final java.lang.String _GUAM = "GUAM";
    public static final java.lang.String _GUATEMALA = "GUATEMALA";
    public static final java.lang.String _GUERNSEY = "GUERNSEY";
    public static final java.lang.String _GUINEA = "GUINEA";
    public static final java.lang.String _GUINEA_BISSAU = "GUINEA_BISSAU";
    public static final java.lang.String _GUYANA = "GUYANA";
    public static final java.lang.String _HAITI = "HAITI";
    public static final java.lang.String _HEARD_ISLAND_AND_MCDONALD_ISLANDS = "HEARD_ISLAND_AND_MCDONALD_ISLANDS";
    public static final java.lang.String _HONDURAS = "HONDURAS";
    public static final java.lang.String _HONG_KONG = "HONG_KONG";
    public static final java.lang.String _HUNGARY = "HUNGARY";
    public static final java.lang.String _ICELAND = "ICELAND";
    public static final java.lang.String _INDIA = "INDIA";
    public static final java.lang.String _INDONESIA = "INDONESIA";
    public static final java.lang.String _IRAN = "IRAN";
    public static final java.lang.String _IRAQ = "IRAQ";
    public static final java.lang.String _IRELAND = "IRELAND";
    public static final java.lang.String _ISRAEL = "ISRAEL";
    public static final java.lang.String _ITALY = "ITALY";
    public static final java.lang.String _JAMAICA = "JAMAICA";
    public static final java.lang.String _JAPAN = "JAPAN";
    public static final java.lang.String _JERSEY = "JERSEY";
    public static final java.lang.String _JORDAN = "JORDAN";
    public static final java.lang.String _KAZAKHSTAN = "KAZAKHSTAN";
    public static final java.lang.String _KENYA = "KENYA";
    public static final java.lang.String _KIRIBATI = "KIRIBATI";
    public static final java.lang.String _NORTH_KOREA = "NORTH_KOREA";
    public static final java.lang.String _SOUTH_KOREA = "SOUTH_KOREA";
    public static final java.lang.String _KUWAIT = "KUWAIT";
    public static final java.lang.String _KUZEY_KIBRIS_TURK_CUMHURIYETI = "KUZEY_KIBRIS_TURK_CUMHURIYETI";
    public static final java.lang.String _KYRGYZSTAN = "KYRGYZSTAN";
    public static final java.lang.String _LAO_PEOPLES_DEMOCRATIC_REPUBLIC = "LAO_PEOPLES_DEMOCRATIC_REPUBLIC";
    public static final java.lang.String _LATVIA = "LATVIA";
    public static final java.lang.String _LEBANON = "LEBANON";
    public static final java.lang.String _LESOTHO = "LESOTHO";
    public static final java.lang.String _LIBERIA = "LIBERIA";
    public static final java.lang.String _LIBYA = "LIBYA";
    public static final java.lang.String _LIECHTENSTEIN = "LIECHTENSTEIN";
    public static final java.lang.String _LITHUANIA = "LITHUANIA";
    public static final java.lang.String _LUXEMBOURG = "LUXEMBOURG";
    public static final java.lang.String _MACAO = "MACAO";
    public static final java.lang.String _MACEDONIA = "MACEDONIA";
    public static final java.lang.String _MADAGASCAR = "MADAGASCAR";
    public static final java.lang.String _MALAWI = "MALAWI";
    public static final java.lang.String _MALAYSIA = "MALAYSIA";
    public static final java.lang.String _MALDIVES = "MALDIVES";
    public static final java.lang.String _MALI = "MALI";
    public static final java.lang.String _MALTA = "MALTA";
    public static final java.lang.String _MARSHALL_ISLANDS = "MARSHALL_ISLANDS";
    public static final java.lang.String _MARTINIQUE = "MARTINIQUE";
    public static final java.lang.String _MAURITANIA = "MAURITANIA";
    public static final java.lang.String _MAURITIUS = "MAURITIUS";
    public static final java.lang.String _MAYOTTE = "MAYOTTE";
    public static final java.lang.String _MEXICO = "MEXICO";
    public static final java.lang.String _MICRONESIA = "MICRONESIA";
    public static final java.lang.String _MOLDOVA = "MOLDOVA";
    public static final java.lang.String _MONACO = "MONACO";
    public static final java.lang.String _MONGOLIA = "MONGOLIA";
    public static final java.lang.String _MONTSERRAT = "MONTSERRAT";
    public static final java.lang.String _MOROCCO = "MOROCCO";
    public static final java.lang.String _MOZAMBIQUE = "MOZAMBIQUE";
    public static final java.lang.String _MYANMAR = "MYANMAR";
    public static final java.lang.String _NAMIBIA = "NAMIBIA";
    public static final java.lang.String _NAURU = "NAURU";
    public static final java.lang.String _NEPAL = "NEPAL";
    public static final java.lang.String _NETHERLANDS = "NETHERLANDS";
    public static final java.lang.String _NETHERLANDS_ANTILLES = "NETHERLANDS_ANTILLES";
    public static final java.lang.String _NEW_CALEDONIA = "NEW_CALEDONIA";
    public static final java.lang.String _NEW_ZEALAND = "NEW_ZEALAND";
    public static final java.lang.String _NICARAGUA = "NICARAGUA";
    public static final java.lang.String _NIGER = "NIGER";
    public static final java.lang.String _NIGERIA = "NIGERIA";
    public static final java.lang.String _NIUE = "NIUE";
    public static final java.lang.String _NORFOLK_ISLAND = "NORFOLK_ISLAND";
    public static final java.lang.String _NORTHERN_MARIANA_ISLANDS = "NORTHERN_MARIANA_ISLANDS";
    public static final java.lang.String _NORWAY = "NORWAY";
    public static final java.lang.String _OMAN = "OMAN";
    public static final java.lang.String _PAKISTAN = "PAKISTAN";
    public static final java.lang.String _PALAU = "PALAU";
    public static final java.lang.String _PALESTINIAN_TERRITORIES = "PALESTINIAN_TERRITORIES";
    public static final java.lang.String _PANAMA = "PANAMA";
    public static final java.lang.String _PAPUA_NEW_GUINEA = "PAPUA_NEW_GUINEA";
    public static final java.lang.String _PARAGUAY = "PARAGUAY";
    public static final java.lang.String _PERU = "PERU";
    public static final java.lang.String _PHILIPPINES = "PHILIPPINES";
    public static final java.lang.String _PITCAIRN = "PITCAIRN";
    public static final java.lang.String _POLAND = "POLAND";
    public static final java.lang.String _PORTUGAL = "PORTUGAL";
    public static final java.lang.String _PUERTO_RICO = "PUERTO_RICO";
    public static final java.lang.String _QATAR = "QATAR";
    public static final java.lang.String _REPUBLIC_OF_KOSOVO = "REPUBLIC_OF_KOSOVO";
    public static final java.lang.String _RÉUNION = "RÉUNION";
    public static final java.lang.String _ROMANIA = "ROMANIA";
    public static final java.lang.String _RUSSIAN_FEDERATION = "RUSSIAN_FEDERATION";
    public static final java.lang.String _RWANDA = "RWANDA";
    public static final java.lang.String _SAINT_HELENA = "SAINT_HELENA";
    public static final java.lang.String _SAINT_KITTS_AND_NEVIS = "SAINT_KITTS_AND_NEVIS";
    public static final java.lang.String _SAINT_LUCIA = "SAINT_LUCIA";
    public static final java.lang.String _SAINT_PIERRE_AND_MIQUELON = "SAINT_PIERRE_AND_MIQUELON";
    public static final java.lang.String _SAINT_VINCENT_AND_THE_GRENADINES = "SAINT_VINCENT_AND_THE_GRENADINES";
    public static final java.lang.String _SAMOA = "SAMOA";
    public static final java.lang.String _SAN_MARINO = "SAN_MARINO";
    public static final java.lang.String _SAO_TOME_AND_PRINCIPE = "SAO_TOME_AND_PRINCIPE";
    public static final java.lang.String _SAUDI_ARABIA = "SAUDI_ARABIA";
    public static final java.lang.String _SENEGAL = "SENEGAL";
    public static final java.lang.String _SERBIA_AND_MONTENEGRO = "SERBIA_AND_MONTENEGRO";
    public static final java.lang.String _SEYCHELLES = "SEYCHELLES";
    public static final java.lang.String _SIERRA_LEONE = "SIERRA_LEONE";
    public static final java.lang.String _SINGAPORE = "SINGAPORE";
    public static final java.lang.String _SLOVAKIA = "SLOVAKIA";
    public static final java.lang.String _SLOVENIA = "SLOVENIA";
    public static final java.lang.String _SOLOMON_ISLANDS = "SOLOMON_ISLANDS";
    public static final java.lang.String _SOMALIA = "SOMALIA";
    public static final java.lang.String _SOUTH_AFRICA = "SOUTH_AFRICA";
    public static final java.lang.String _SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = "SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS";
    public static final java.lang.String _SPAIN = "SPAIN";
    public static final java.lang.String _SRI_LANKA = "SRI_LANKA";
    public static final java.lang.String _SUDAN = "SUDAN";
    public static final java.lang.String _SURINAME = "SURINAME";
    public static final java.lang.String _SVALBARD_AND_JAN_MAYEN = "SVALBARD_AND_JAN_MAYEN";
    public static final java.lang.String _SWAZILAND = "SWAZILAND";
    public static final java.lang.String _SWEDEN = "SWEDEN";
    public static final java.lang.String _SWITZERLAND = "SWITZERLAND";
    public static final java.lang.String _SYRIAN_ARAB_REPUBLIC = "SYRIAN_ARAB_REPUBLIC";
    public static final java.lang.String _TAIWAN = "TAIWAN";
    public static final java.lang.String _TAJIKISTAN = "TAJIKISTAN";
    public static final java.lang.String _TANZANIA = "TANZANIA";
    public static final java.lang.String _THAILAND = "THAILAND";
    public static final java.lang.String _TIMOR_LESTE = "TIMOR_LESTE";
    public static final java.lang.String _TOGO = "TOGO";
    public static final java.lang.String _TOKELAU = "TOKELAU";
    public static final java.lang.String _TONGA = "TONGA";
    public static final java.lang.String _TRINIDAD_AND_TOBAGO = "TRINIDAD_AND_TOBAGO";
    public static final java.lang.String _TUNISIA = "TUNISIA";
    public static final java.lang.String _TURKMENISTAN = "TURKMENISTAN";
    public static final java.lang.String _TURKS_AND_CAICOS_ISLANDS = "TURKS_AND_CAICOS_ISLANDS";
    public static final java.lang.String _TUVALU = "TUVALU";
    public static final java.lang.String _UGANDA = "UGANDA";
    public static final java.lang.String _UKRAINE = "UKRAINE";
    public static final java.lang.String _UNITED_ARAB_EMIRATES = "UNITED_ARAB_EMIRATES";
    public static final java.lang.String _UNITED_KINGDOM = "UNITED_KINGDOM";
    public static final java.lang.String _UNITED_STATES = "UNITED_STATES";
    public static final java.lang.String _UNITED_STATES_MINOR_OUTLYING_ISLANDS = "UNITED_STATES_MINOR_OUTLYING_ISLANDS";
    public static final java.lang.String _URUGUAY = "URUGUAY";
    public static final java.lang.String _UZBEKISTAN = "UZBEKISTAN";
    public static final java.lang.String _VANUATU = "VANUATU";
    public static final java.lang.String _VATICAN_CITY = "VATICAN_CITY";
    public static final java.lang.String _VENEZUELA = "VENEZUELA";
    public static final java.lang.String _VIET_NAM = "VIET_NAM";
    public static final java.lang.String _VIRGIN_ISLANDS_BRITISH = "VIRGIN_ISLANDS_BRITISH";
    public static final java.lang.String _VIRGIN_ISLANDS_US = "VIRGIN_ISLANDS_US";
    public static final java.lang.String _WALLIS_AND_FUTUNA = "WALLIS_AND_FUTUNA";
    public static final java.lang.String _WESTERN_SAHARA = "WESTERN_SAHARA";
    public static final java.lang.String _YEMEN = "YEMEN";
    public static final java.lang.String _ZAMBIA = "ZAMBIA";
    public static final java.lang.String _ZIMBABWE = "ZIMBABWE";
    public static final SnfEnumUlkeler TANIMSIZ = new SnfEnumUlkeler(_TANIMSIZ);
    public static final SnfEnumUlkeler TURKIYE = new SnfEnumUlkeler(_TURKIYE);
    public static final SnfEnumUlkeler AFGHANISTAN = new SnfEnumUlkeler(_AFGHANISTAN);
    public static final SnfEnumUlkeler ALBANIA = new SnfEnumUlkeler(_ALBANIA);
    public static final SnfEnumUlkeler ALGERIA = new SnfEnumUlkeler(_ALGERIA);
    public static final SnfEnumUlkeler AMERICAN_SAMOA = new SnfEnumUlkeler(_AMERICAN_SAMOA);
    public static final SnfEnumUlkeler ANDORRA = new SnfEnumUlkeler(_ANDORRA);
    public static final SnfEnumUlkeler ANGOLA = new SnfEnumUlkeler(_ANGOLA);
    public static final SnfEnumUlkeler ANGUILLA = new SnfEnumUlkeler(_ANGUILLA);
    public static final SnfEnumUlkeler ANTARCTICA = new SnfEnumUlkeler(_ANTARCTICA);
    public static final SnfEnumUlkeler ANTIGUA_AND_BARBUDA = new SnfEnumUlkeler(_ANTIGUA_AND_BARBUDA);
    public static final SnfEnumUlkeler ARGENTINA = new SnfEnumUlkeler(_ARGENTINA);
    public static final SnfEnumUlkeler ARMENIA = new SnfEnumUlkeler(_ARMENIA);
    public static final SnfEnumUlkeler ARUBA = new SnfEnumUlkeler(_ARUBA);
    public static final SnfEnumUlkeler AUSTRALIA = new SnfEnumUlkeler(_AUSTRALIA);
    public static final SnfEnumUlkeler AUSTRIA = new SnfEnumUlkeler(_AUSTRIA);
    public static final SnfEnumUlkeler AZERBAIJAN = new SnfEnumUlkeler(_AZERBAIJAN);
    public static final SnfEnumUlkeler BAHAMAS = new SnfEnumUlkeler(_BAHAMAS);
    public static final SnfEnumUlkeler BAHRAIN = new SnfEnumUlkeler(_BAHRAIN);
    public static final SnfEnumUlkeler BANGLADESH = new SnfEnumUlkeler(_BANGLADESH);
    public static final SnfEnumUlkeler BARBADOS = new SnfEnumUlkeler(_BARBADOS);
    public static final SnfEnumUlkeler BELARUS = new SnfEnumUlkeler(_BELARUS);
    public static final SnfEnumUlkeler BELGIUM = new SnfEnumUlkeler(_BELGIUM);
    public static final SnfEnumUlkeler BELIZE = new SnfEnumUlkeler(_BELIZE);
    public static final SnfEnumUlkeler BENIN = new SnfEnumUlkeler(_BENIN);
    public static final SnfEnumUlkeler BERMUDA = new SnfEnumUlkeler(_BERMUDA);
    public static final SnfEnumUlkeler BHUTAN = new SnfEnumUlkeler(_BHUTAN);
    public static final SnfEnumUlkeler BOLIVIA = new SnfEnumUlkeler(_BOLIVIA);
    public static final SnfEnumUlkeler BOSNIA_AND_HERZEGOVINA = new SnfEnumUlkeler(_BOSNIA_AND_HERZEGOVINA);
    public static final SnfEnumUlkeler BOTSWANA = new SnfEnumUlkeler(_BOTSWANA);
    public static final SnfEnumUlkeler BOUVET_ISLAND = new SnfEnumUlkeler(_BOUVET_ISLAND);
    public static final SnfEnumUlkeler BRAZIL = new SnfEnumUlkeler(_BRAZIL);
    public static final SnfEnumUlkeler BRITISH_INDIAN_OCEAN_TERRITORY = new SnfEnumUlkeler(_BRITISH_INDIAN_OCEAN_TERRITORY);
    public static final SnfEnumUlkeler BRUNEI_DARUSSALAM = new SnfEnumUlkeler(_BRUNEI_DARUSSALAM);
    public static final SnfEnumUlkeler BULGARIA = new SnfEnumUlkeler(_BULGARIA);
    public static final SnfEnumUlkeler BURKINA_FASO = new SnfEnumUlkeler(_BURKINA_FASO);
    public static final SnfEnumUlkeler BURUNDI = new SnfEnumUlkeler(_BURUNDI);
    public static final SnfEnumUlkeler CAMBODIA = new SnfEnumUlkeler(_CAMBODIA);
    public static final SnfEnumUlkeler CAMEROON = new SnfEnumUlkeler(_CAMEROON);
    public static final SnfEnumUlkeler CANADA = new SnfEnumUlkeler(_CANADA);
    public static final SnfEnumUlkeler CAPE_VERDE = new SnfEnumUlkeler(_CAPE_VERDE);
    public static final SnfEnumUlkeler CAYMAN_ISLANDS = new SnfEnumUlkeler(_CAYMAN_ISLANDS);
    public static final SnfEnumUlkeler CENTRAL_AFRICAN_REPUBLIC = new SnfEnumUlkeler(_CENTRAL_AFRICAN_REPUBLIC);
    public static final SnfEnumUlkeler CHAD = new SnfEnumUlkeler(_CHAD);
    public static final SnfEnumUlkeler CHILE = new SnfEnumUlkeler(_CHILE);
    public static final SnfEnumUlkeler CHINA = new SnfEnumUlkeler(_CHINA);
    public static final SnfEnumUlkeler CHRISTMAS_ISLAND = new SnfEnumUlkeler(_CHRISTMAS_ISLAND);
    public static final SnfEnumUlkeler COCOS_KEELING_ISLANDS = new SnfEnumUlkeler(_COCOS_KEELING_ISLANDS);
    public static final SnfEnumUlkeler COLOMBIA = new SnfEnumUlkeler(_COLOMBIA);
    public static final SnfEnumUlkeler COMOROS = new SnfEnumUlkeler(_COMOROS);
    public static final SnfEnumUlkeler CONGO_REPUBLIC_OF = new SnfEnumUlkeler(_CONGO_REPUBLIC_OF);
    public static final SnfEnumUlkeler CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE_formerly_Zaire = new SnfEnumUlkeler(_CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE_formerly_Zaire);
    public static final SnfEnumUlkeler COOK_ISLANDS = new SnfEnumUlkeler(_COOK_ISLANDS);
    public static final SnfEnumUlkeler COSTA_RICA = new SnfEnumUlkeler(_COSTA_RICA);
    public static final SnfEnumUlkeler CÔTE_DIVOIRE_Ivory_Coast = new SnfEnumUlkeler(_CÔTE_DIVOIRE_Ivory_Coast);
    public static final SnfEnumUlkeler CROATIA_Hrvatska = new SnfEnumUlkeler(_CROATIA_Hrvatska);
    public static final SnfEnumUlkeler CUBA = new SnfEnumUlkeler(_CUBA);
    public static final SnfEnumUlkeler CYPRUS = new SnfEnumUlkeler(_CYPRUS);
    public static final SnfEnumUlkeler CZECH_REPUBLIC = new SnfEnumUlkeler(_CZECH_REPUBLIC);
    public static final SnfEnumUlkeler DENMARK = new SnfEnumUlkeler(_DENMARK);
    public static final SnfEnumUlkeler DJIBOUTI = new SnfEnumUlkeler(_DJIBOUTI);
    public static final SnfEnumUlkeler DOMINICA = new SnfEnumUlkeler(_DOMINICA);
    public static final SnfEnumUlkeler DOMINICAN_REPUBLIC = new SnfEnumUlkeler(_DOMINICAN_REPUBLIC);
    public static final SnfEnumUlkeler ECUADOR = new SnfEnumUlkeler(_ECUADOR);
    public static final SnfEnumUlkeler EGYPT = new SnfEnumUlkeler(_EGYPT);
    public static final SnfEnumUlkeler EL_SALVADOR = new SnfEnumUlkeler(_EL_SALVADOR);
    public static final SnfEnumUlkeler EQUATORIAL_GUINEA = new SnfEnumUlkeler(_EQUATORIAL_GUINEA);
    public static final SnfEnumUlkeler ERITREA = new SnfEnumUlkeler(_ERITREA);
    public static final SnfEnumUlkeler ESTONIA = new SnfEnumUlkeler(_ESTONIA);
    public static final SnfEnumUlkeler ETHIOPIA = new SnfEnumUlkeler(_ETHIOPIA);
    public static final SnfEnumUlkeler FAEROE_ISLANDS = new SnfEnumUlkeler(_FAEROE_ISLANDS);
    public static final SnfEnumUlkeler FALKLAND_ISLANDS_MALVINAS = new SnfEnumUlkeler(_FALKLAND_ISLANDS_MALVINAS);
    public static final SnfEnumUlkeler FIJI = new SnfEnumUlkeler(_FIJI);
    public static final SnfEnumUlkeler FINLAND = new SnfEnumUlkeler(_FINLAND);
    public static final SnfEnumUlkeler FRANCE = new SnfEnumUlkeler(_FRANCE);
    public static final SnfEnumUlkeler FRENCH_GUIANA = new SnfEnumUlkeler(_FRENCH_GUIANA);
    public static final SnfEnumUlkeler FRENCH_POLYNESIA = new SnfEnumUlkeler(_FRENCH_POLYNESIA);
    public static final SnfEnumUlkeler FRENCH_SOUTHERN_TERRITORIES = new SnfEnumUlkeler(_FRENCH_SOUTHERN_TERRITORIES);
    public static final SnfEnumUlkeler GABON = new SnfEnumUlkeler(_GABON);
    public static final SnfEnumUlkeler GAMBIA = new SnfEnumUlkeler(_GAMBIA);
    public static final SnfEnumUlkeler GEORGIA = new SnfEnumUlkeler(_GEORGIA);
    public static final SnfEnumUlkeler GERMANY = new SnfEnumUlkeler(_GERMANY);
    public static final SnfEnumUlkeler GHANA = new SnfEnumUlkeler(_GHANA);
    public static final SnfEnumUlkeler GIBRALTAR = new SnfEnumUlkeler(_GIBRALTAR);
    public static final SnfEnumUlkeler GREECE = new SnfEnumUlkeler(_GREECE);
    public static final SnfEnumUlkeler GREENLAND = new SnfEnumUlkeler(_GREENLAND);
    public static final SnfEnumUlkeler GRENADA = new SnfEnumUlkeler(_GRENADA);
    public static final SnfEnumUlkeler GUADELOUPE = new SnfEnumUlkeler(_GUADELOUPE);
    public static final SnfEnumUlkeler GUAM = new SnfEnumUlkeler(_GUAM);
    public static final SnfEnumUlkeler GUATEMALA = new SnfEnumUlkeler(_GUATEMALA);
    public static final SnfEnumUlkeler GUERNSEY = new SnfEnumUlkeler(_GUERNSEY);
    public static final SnfEnumUlkeler GUINEA = new SnfEnumUlkeler(_GUINEA);
    public static final SnfEnumUlkeler GUINEA_BISSAU = new SnfEnumUlkeler(_GUINEA_BISSAU);
    public static final SnfEnumUlkeler GUYANA = new SnfEnumUlkeler(_GUYANA);
    public static final SnfEnumUlkeler HAITI = new SnfEnumUlkeler(_HAITI);
    public static final SnfEnumUlkeler HEARD_ISLAND_AND_MCDONALD_ISLANDS = new SnfEnumUlkeler(_HEARD_ISLAND_AND_MCDONALD_ISLANDS);
    public static final SnfEnumUlkeler HONDURAS = new SnfEnumUlkeler(_HONDURAS);
    public static final SnfEnumUlkeler HONG_KONG = new SnfEnumUlkeler(_HONG_KONG);
    public static final SnfEnumUlkeler HUNGARY = new SnfEnumUlkeler(_HUNGARY);
    public static final SnfEnumUlkeler ICELAND = new SnfEnumUlkeler(_ICELAND);
    public static final SnfEnumUlkeler INDIA = new SnfEnumUlkeler(_INDIA);
    public static final SnfEnumUlkeler INDONESIA = new SnfEnumUlkeler(_INDONESIA);
    public static final SnfEnumUlkeler IRAN = new SnfEnumUlkeler(_IRAN);
    public static final SnfEnumUlkeler IRAQ = new SnfEnumUlkeler(_IRAQ);
    public static final SnfEnumUlkeler IRELAND = new SnfEnumUlkeler(_IRELAND);
    public static final SnfEnumUlkeler ISRAEL = new SnfEnumUlkeler(_ISRAEL);
    public static final SnfEnumUlkeler ITALY = new SnfEnumUlkeler(_ITALY);
    public static final SnfEnumUlkeler JAMAICA = new SnfEnumUlkeler(_JAMAICA);
    public static final SnfEnumUlkeler JAPAN = new SnfEnumUlkeler(_JAPAN);
    public static final SnfEnumUlkeler JERSEY = new SnfEnumUlkeler(_JERSEY);
    public static final SnfEnumUlkeler JORDAN = new SnfEnumUlkeler(_JORDAN);
    public static final SnfEnumUlkeler KAZAKHSTAN = new SnfEnumUlkeler(_KAZAKHSTAN);
    public static final SnfEnumUlkeler KENYA = new SnfEnumUlkeler(_KENYA);
    public static final SnfEnumUlkeler KIRIBATI = new SnfEnumUlkeler(_KIRIBATI);
    public static final SnfEnumUlkeler NORTH_KOREA = new SnfEnumUlkeler(_NORTH_KOREA);
    public static final SnfEnumUlkeler SOUTH_KOREA = new SnfEnumUlkeler(_SOUTH_KOREA);
    public static final SnfEnumUlkeler KUWAIT = new SnfEnumUlkeler(_KUWAIT);
    public static final SnfEnumUlkeler KUZEY_KIBRIS_TURK_CUMHURIYETI = new SnfEnumUlkeler(_KUZEY_KIBRIS_TURK_CUMHURIYETI);
    public static final SnfEnumUlkeler KYRGYZSTAN = new SnfEnumUlkeler(_KYRGYZSTAN);
    public static final SnfEnumUlkeler LAO_PEOPLES_DEMOCRATIC_REPUBLIC = new SnfEnumUlkeler(_LAO_PEOPLES_DEMOCRATIC_REPUBLIC);
    public static final SnfEnumUlkeler LATVIA = new SnfEnumUlkeler(_LATVIA);
    public static final SnfEnumUlkeler LEBANON = new SnfEnumUlkeler(_LEBANON);
    public static final SnfEnumUlkeler LESOTHO = new SnfEnumUlkeler(_LESOTHO);
    public static final SnfEnumUlkeler LIBERIA = new SnfEnumUlkeler(_LIBERIA);
    public static final SnfEnumUlkeler LIBYA = new SnfEnumUlkeler(_LIBYA);
    public static final SnfEnumUlkeler LIECHTENSTEIN = new SnfEnumUlkeler(_LIECHTENSTEIN);
    public static final SnfEnumUlkeler LITHUANIA = new SnfEnumUlkeler(_LITHUANIA);
    public static final SnfEnumUlkeler LUXEMBOURG = new SnfEnumUlkeler(_LUXEMBOURG);
    public static final SnfEnumUlkeler MACAO = new SnfEnumUlkeler(_MACAO);
    public static final SnfEnumUlkeler MACEDONIA = new SnfEnumUlkeler(_MACEDONIA);
    public static final SnfEnumUlkeler MADAGASCAR = new SnfEnumUlkeler(_MADAGASCAR);
    public static final SnfEnumUlkeler MALAWI = new SnfEnumUlkeler(_MALAWI);
    public static final SnfEnumUlkeler MALAYSIA = new SnfEnumUlkeler(_MALAYSIA);
    public static final SnfEnumUlkeler MALDIVES = new SnfEnumUlkeler(_MALDIVES);
    public static final SnfEnumUlkeler MALI = new SnfEnumUlkeler(_MALI);
    public static final SnfEnumUlkeler MALTA = new SnfEnumUlkeler(_MALTA);
    public static final SnfEnumUlkeler MARSHALL_ISLANDS = new SnfEnumUlkeler(_MARSHALL_ISLANDS);
    public static final SnfEnumUlkeler MARTINIQUE = new SnfEnumUlkeler(_MARTINIQUE);
    public static final SnfEnumUlkeler MAURITANIA = new SnfEnumUlkeler(_MAURITANIA);
    public static final SnfEnumUlkeler MAURITIUS = new SnfEnumUlkeler(_MAURITIUS);
    public static final SnfEnumUlkeler MAYOTTE = new SnfEnumUlkeler(_MAYOTTE);
    public static final SnfEnumUlkeler MEXICO = new SnfEnumUlkeler(_MEXICO);
    public static final SnfEnumUlkeler MICRONESIA = new SnfEnumUlkeler(_MICRONESIA);
    public static final SnfEnumUlkeler MOLDOVA = new SnfEnumUlkeler(_MOLDOVA);
    public static final SnfEnumUlkeler MONACO = new SnfEnumUlkeler(_MONACO);
    public static final SnfEnumUlkeler MONGOLIA = new SnfEnumUlkeler(_MONGOLIA);
    public static final SnfEnumUlkeler MONTSERRAT = new SnfEnumUlkeler(_MONTSERRAT);
    public static final SnfEnumUlkeler MOROCCO = new SnfEnumUlkeler(_MOROCCO);
    public static final SnfEnumUlkeler MOZAMBIQUE = new SnfEnumUlkeler(_MOZAMBIQUE);
    public static final SnfEnumUlkeler MYANMAR = new SnfEnumUlkeler(_MYANMAR);
    public static final SnfEnumUlkeler NAMIBIA = new SnfEnumUlkeler(_NAMIBIA);
    public static final SnfEnumUlkeler NAURU = new SnfEnumUlkeler(_NAURU);
    public static final SnfEnumUlkeler NEPAL = new SnfEnumUlkeler(_NEPAL);
    public static final SnfEnumUlkeler NETHERLANDS = new SnfEnumUlkeler(_NETHERLANDS);
    public static final SnfEnumUlkeler NETHERLANDS_ANTILLES = new SnfEnumUlkeler(_NETHERLANDS_ANTILLES);
    public static final SnfEnumUlkeler NEW_CALEDONIA = new SnfEnumUlkeler(_NEW_CALEDONIA);
    public static final SnfEnumUlkeler NEW_ZEALAND = new SnfEnumUlkeler(_NEW_ZEALAND);
    public static final SnfEnumUlkeler NICARAGUA = new SnfEnumUlkeler(_NICARAGUA);
    public static final SnfEnumUlkeler NIGER = new SnfEnumUlkeler(_NIGER);
    public static final SnfEnumUlkeler NIGERIA = new SnfEnumUlkeler(_NIGERIA);
    public static final SnfEnumUlkeler NIUE = new SnfEnumUlkeler(_NIUE);
    public static final SnfEnumUlkeler NORFOLK_ISLAND = new SnfEnumUlkeler(_NORFOLK_ISLAND);
    public static final SnfEnumUlkeler NORTHERN_MARIANA_ISLANDS = new SnfEnumUlkeler(_NORTHERN_MARIANA_ISLANDS);
    public static final SnfEnumUlkeler NORWAY = new SnfEnumUlkeler(_NORWAY);
    public static final SnfEnumUlkeler OMAN = new SnfEnumUlkeler(_OMAN);
    public static final SnfEnumUlkeler PAKISTAN = new SnfEnumUlkeler(_PAKISTAN);
    public static final SnfEnumUlkeler PALAU = new SnfEnumUlkeler(_PALAU);
    public static final SnfEnumUlkeler PALESTINIAN_TERRITORIES = new SnfEnumUlkeler(_PALESTINIAN_TERRITORIES);
    public static final SnfEnumUlkeler PANAMA = new SnfEnumUlkeler(_PANAMA);
    public static final SnfEnumUlkeler PAPUA_NEW_GUINEA = new SnfEnumUlkeler(_PAPUA_NEW_GUINEA);
    public static final SnfEnumUlkeler PARAGUAY = new SnfEnumUlkeler(_PARAGUAY);
    public static final SnfEnumUlkeler PERU = new SnfEnumUlkeler(_PERU);
    public static final SnfEnumUlkeler PHILIPPINES = new SnfEnumUlkeler(_PHILIPPINES);
    public static final SnfEnumUlkeler PITCAIRN = new SnfEnumUlkeler(_PITCAIRN);
    public static final SnfEnumUlkeler POLAND = new SnfEnumUlkeler(_POLAND);
    public static final SnfEnumUlkeler PORTUGAL = new SnfEnumUlkeler(_PORTUGAL);
    public static final SnfEnumUlkeler PUERTO_RICO = new SnfEnumUlkeler(_PUERTO_RICO);
    public static final SnfEnumUlkeler QATAR = new SnfEnumUlkeler(_QATAR);
    public static final SnfEnumUlkeler REPUBLIC_OF_KOSOVO = new SnfEnumUlkeler(_REPUBLIC_OF_KOSOVO);
    public static final SnfEnumUlkeler RÉUNION = new SnfEnumUlkeler(_RÉUNION);
    public static final SnfEnumUlkeler ROMANIA = new SnfEnumUlkeler(_ROMANIA);
    public static final SnfEnumUlkeler RUSSIAN_FEDERATION = new SnfEnumUlkeler(_RUSSIAN_FEDERATION);
    public static final SnfEnumUlkeler RWANDA = new SnfEnumUlkeler(_RWANDA);
    public static final SnfEnumUlkeler SAINT_HELENA = new SnfEnumUlkeler(_SAINT_HELENA);
    public static final SnfEnumUlkeler SAINT_KITTS_AND_NEVIS = new SnfEnumUlkeler(_SAINT_KITTS_AND_NEVIS);
    public static final SnfEnumUlkeler SAINT_LUCIA = new SnfEnumUlkeler(_SAINT_LUCIA);
    public static final SnfEnumUlkeler SAINT_PIERRE_AND_MIQUELON = new SnfEnumUlkeler(_SAINT_PIERRE_AND_MIQUELON);
    public static final SnfEnumUlkeler SAINT_VINCENT_AND_THE_GRENADINES = new SnfEnumUlkeler(_SAINT_VINCENT_AND_THE_GRENADINES);
    public static final SnfEnumUlkeler SAMOA = new SnfEnumUlkeler(_SAMOA);
    public static final SnfEnumUlkeler SAN_MARINO = new SnfEnumUlkeler(_SAN_MARINO);
    public static final SnfEnumUlkeler SAO_TOME_AND_PRINCIPE = new SnfEnumUlkeler(_SAO_TOME_AND_PRINCIPE);
    public static final SnfEnumUlkeler SAUDI_ARABIA = new SnfEnumUlkeler(_SAUDI_ARABIA);
    public static final SnfEnumUlkeler SENEGAL = new SnfEnumUlkeler(_SENEGAL);
    public static final SnfEnumUlkeler SERBIA_AND_MONTENEGRO = new SnfEnumUlkeler(_SERBIA_AND_MONTENEGRO);
    public static final SnfEnumUlkeler SEYCHELLES = new SnfEnumUlkeler(_SEYCHELLES);
    public static final SnfEnumUlkeler SIERRA_LEONE = new SnfEnumUlkeler(_SIERRA_LEONE);
    public static final SnfEnumUlkeler SINGAPORE = new SnfEnumUlkeler(_SINGAPORE);
    public static final SnfEnumUlkeler SLOVAKIA = new SnfEnumUlkeler(_SLOVAKIA);
    public static final SnfEnumUlkeler SLOVENIA = new SnfEnumUlkeler(_SLOVENIA);
    public static final SnfEnumUlkeler SOLOMON_ISLANDS = new SnfEnumUlkeler(_SOLOMON_ISLANDS);
    public static final SnfEnumUlkeler SOMALIA = new SnfEnumUlkeler(_SOMALIA);
    public static final SnfEnumUlkeler SOUTH_AFRICA = new SnfEnumUlkeler(_SOUTH_AFRICA);
    public static final SnfEnumUlkeler SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = new SnfEnumUlkeler(_SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS);
    public static final SnfEnumUlkeler SPAIN = new SnfEnumUlkeler(_SPAIN);
    public static final SnfEnumUlkeler SRI_LANKA = new SnfEnumUlkeler(_SRI_LANKA);
    public static final SnfEnumUlkeler SUDAN = new SnfEnumUlkeler(_SUDAN);
    public static final SnfEnumUlkeler SURINAME = new SnfEnumUlkeler(_SURINAME);
    public static final SnfEnumUlkeler SVALBARD_AND_JAN_MAYEN = new SnfEnumUlkeler(_SVALBARD_AND_JAN_MAYEN);
    public static final SnfEnumUlkeler SWAZILAND = new SnfEnumUlkeler(_SWAZILAND);
    public static final SnfEnumUlkeler SWEDEN = new SnfEnumUlkeler(_SWEDEN);
    public static final SnfEnumUlkeler SWITZERLAND = new SnfEnumUlkeler(_SWITZERLAND);
    public static final SnfEnumUlkeler SYRIAN_ARAB_REPUBLIC = new SnfEnumUlkeler(_SYRIAN_ARAB_REPUBLIC);
    public static final SnfEnumUlkeler TAIWAN = new SnfEnumUlkeler(_TAIWAN);
    public static final SnfEnumUlkeler TAJIKISTAN = new SnfEnumUlkeler(_TAJIKISTAN);
    public static final SnfEnumUlkeler TANZANIA = new SnfEnumUlkeler(_TANZANIA);
    public static final SnfEnumUlkeler THAILAND = new SnfEnumUlkeler(_THAILAND);
    public static final SnfEnumUlkeler TIMOR_LESTE = new SnfEnumUlkeler(_TIMOR_LESTE);
    public static final SnfEnumUlkeler TOGO = new SnfEnumUlkeler(_TOGO);
    public static final SnfEnumUlkeler TOKELAU = new SnfEnumUlkeler(_TOKELAU);
    public static final SnfEnumUlkeler TONGA = new SnfEnumUlkeler(_TONGA);
    public static final SnfEnumUlkeler TRINIDAD_AND_TOBAGO = new SnfEnumUlkeler(_TRINIDAD_AND_TOBAGO);
    public static final SnfEnumUlkeler TUNISIA = new SnfEnumUlkeler(_TUNISIA);
    public static final SnfEnumUlkeler TURKMENISTAN = new SnfEnumUlkeler(_TURKMENISTAN);
    public static final SnfEnumUlkeler TURKS_AND_CAICOS_ISLANDS = new SnfEnumUlkeler(_TURKS_AND_CAICOS_ISLANDS);
    public static final SnfEnumUlkeler TUVALU = new SnfEnumUlkeler(_TUVALU);
    public static final SnfEnumUlkeler UGANDA = new SnfEnumUlkeler(_UGANDA);
    public static final SnfEnumUlkeler UKRAINE = new SnfEnumUlkeler(_UKRAINE);
    public static final SnfEnumUlkeler UNITED_ARAB_EMIRATES = new SnfEnumUlkeler(_UNITED_ARAB_EMIRATES);
    public static final SnfEnumUlkeler UNITED_KINGDOM = new SnfEnumUlkeler(_UNITED_KINGDOM);
    public static final SnfEnumUlkeler UNITED_STATES = new SnfEnumUlkeler(_UNITED_STATES);
    public static final SnfEnumUlkeler UNITED_STATES_MINOR_OUTLYING_ISLANDS = new SnfEnumUlkeler(_UNITED_STATES_MINOR_OUTLYING_ISLANDS);
    public static final SnfEnumUlkeler URUGUAY = new SnfEnumUlkeler(_URUGUAY);
    public static final SnfEnumUlkeler UZBEKISTAN = new SnfEnumUlkeler(_UZBEKISTAN);
    public static final SnfEnumUlkeler VANUATU = new SnfEnumUlkeler(_VANUATU);
    public static final SnfEnumUlkeler VATICAN_CITY = new SnfEnumUlkeler(_VATICAN_CITY);
    public static final SnfEnumUlkeler VENEZUELA = new SnfEnumUlkeler(_VENEZUELA);
    public static final SnfEnumUlkeler VIET_NAM = new SnfEnumUlkeler(_VIET_NAM);
    public static final SnfEnumUlkeler VIRGIN_ISLANDS_BRITISH = new SnfEnumUlkeler(_VIRGIN_ISLANDS_BRITISH);
    public static final SnfEnumUlkeler VIRGIN_ISLANDS_US = new SnfEnumUlkeler(_VIRGIN_ISLANDS_US);
    public static final SnfEnumUlkeler WALLIS_AND_FUTUNA = new SnfEnumUlkeler(_WALLIS_AND_FUTUNA);
    public static final SnfEnumUlkeler WESTERN_SAHARA = new SnfEnumUlkeler(_WESTERN_SAHARA);
    public static final SnfEnumUlkeler YEMEN = new SnfEnumUlkeler(_YEMEN);
    public static final SnfEnumUlkeler ZAMBIA = new SnfEnumUlkeler(_ZAMBIA);
    public static final SnfEnumUlkeler ZIMBABWE = new SnfEnumUlkeler(_ZIMBABWE);
    public java.lang.String getValue() { return _value_;}
    public static SnfEnumUlkeler fromValue(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        SnfEnumUlkeler enumeration = (SnfEnumUlkeler)
            _table_.get(value);
        if (enumeration==null) throw new java.lang.IllegalArgumentException();
        return enumeration;
    }
    public static SnfEnumUlkeler fromString(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        return fromValue(value);
    }
    public boolean equals(java.lang.Object obj) {return (obj == this);}
    public int hashCode() { return toString().hashCode();}
    public java.lang.String toString() { return _value_;}
    public java.lang.Object readResolve() throws java.io.ObjectStreamException { return fromValue(_value_);}
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumSerializer(
            _javaType, _xmlType);
    }
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumDeserializer(
            _javaType, _xmlType);
    }
    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(SnfEnumUlkeler.class);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.datacontract.org/2004/07/KBS_Model", "snfEnum.Ulkeler"));
    }
    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

}
